### ISSUE TITLE
replace variables in titles

### ISSUE THREAD

**Issue by runa** [EverythingMe/redash#457]
Query Variables `{{p_foo}}` on the Query String are great, but I would really love if the placeholders would be also replaced in query titles, visualization titles, etc.

Tnx

**Comment by arikfr** [comment]
@runa if there will be proper UI for selecting values for variables, will you still need this?

**Comment by runa** [comment]
Well, I don't really remember why I needed it in the first place; but I think it makes a lot of sense.....

**Comment by arikfr** [comment]
I'm currently working on a UI for query parameters, and it looks like it makes this redundant. Let's revisit and see if this is still needed, after I release the version with the UI.

**Comment by idoDavid** [comment]
Hi,

that's an old one, but I want to add on this - I need the query params in the titles. My usecase: I have params coming from a query (Query based params) usually customers ids/names. I want the visualization to contain the name in the title, mainly since the current refreshing of dashboards takes different time to different panels (based on different queries obviously) and I would like the users of the dashboard to see in the title that the vis was refreshed.

WDYT?
