### ISSUE TITLE
Don't return data source options via API

### ISSUE THREAD

**Issue by captn3m0** [EverythingMe/redash#554]
Currently, the route `api/data_sources/:id` returns the entire data source, including its various config options. Meaning, an authenticated admin essentially gains the direct database credentials.

While this might sound like a tiny issue, since its only accessible to the admin user, it is further complicated by the following:

- No 2 factor auth for admin user
- Getting the database credential will often give an attacker direct access to the database, completely bypassing the authentication flow. If you have made the mistake of connecting to redash via HTTP, your session cookie would be enough for this attack.

Add the fact that there is no brute force protection currently (#51), it becomes a really nice target.

Access Credentials should never be returned by any API. However, I am not sure what (if any) options could be securely returned via the API. Does the database name reveal anything? What if there is no password? I'd very much prefer if all you could do was see the name/type of the data source and delete it.

**Comment by arikfr** [comment]
That's a valid concern, and indeed I think that we should stop sending the password back to the UI. The rest of the options are of less concern, because in the case there is no password, the database won't have public access (or you have bigger worries than having its name in re:dash).

> If you have made the mistake of connecting to redash via HTTP

We mention in the [docs](http://docs.redash.io/en/latest/setup.html#notes) that in production setup users should enforce HTTPS connection to re:dash. Maybe we should emphasize it more. Actually the best practice is to use HTTPS & place it inside a private network, but the later might be too much for some.

**Comment by captn3m0** [comment]
Thanks a lot :+1:
