### ISSUE TITLE
Security fault - Google Oauth Login allows users login without password in the next times

### ISSUE THREAD

**Issue by WesleyBatista** [EverythingMe/redash#559]
Choosing login in with Google Account creates a user in the db and then login him into the system.

The password column is fulfilled with a hash of an empty string in the user creation time.

The next logins into the system allows anyone only put the email of the user and leave the password field empty.

**Comment by arikfr** [comment]
I've just checked it on the [demo instance](http://demo.redash.io), and new users get created with `password_hash` value set to `null`. Note that `null` value isn't the same as empty password -- because when there is no `password_hash` set, [`verify_password`](https://github.com/EverythingMe/redash/blob/master/redash/models.py#L237) will return false.

Have you actually logged in without a password? In that case, can you check the `password_hash` value of the user you used to login?

I'm closing this issue, and let's continue further communication over email (arik@arikfr.com), to avoid disclosing a security vulnerability before there is a fix.

Thanks!
