### ISSUE TITLE
"'float' object is not iterable" when using coordinates for MongoDB query

### ISSUE THREAD

**Issue by macecchi** [EverythingMe/redash#597]
I'm trying to run a query using **MongoDB** and the **[$geoNear](http://docs.mongodb.org/manual/reference/operator/aggregation/geoNear/)** function, but every time I type the origin coordinate using floats (to create a [GeoJSON Point](http://docs.mongodb.org/manual/reference/geojson/)), I get an error: [*from Python?*]

 `Error running query: 'float' object is not iterable`

I'm trying to run the query below. The problem here is the `[ -22.910079, -43.205161 ]` part.

```json
{
  "collection": "bus",
  "aggregate": [
    { 
    	"$geoNear": { 
    		"near": { "type": "Point", "coordinates": [ -22.910079, -43.205161 ] },
    		"maxDistance": 100000000,
    		"distanceField": "dist.calculated",
        	"includeLocs": "dist.location",
        	"spherical": true
    	}
    }    
  ]
}
```

However, if I use the coordinates with integers, such as `[ -22, -43 ]`, the query runs fine, but this coordinate is now meaningless, obviously. Here is an example that doesn't error:

```json
{
  "collection": "bus",
  "aggregate": [
    { 
    	"$geoNear": { 
    		"near": { "type": "Point", "coordinates": [ -22, -43 ] },
    		"maxDistance": 100000000,
    		"distanceField": "dist.calculated",
        	"includeLocs": "dist.location",
        	"spherical": true
    	}
    }    
  ]
}
```

**Comment by arikfr** [comment]
I think the issue is this line:
https://github.com/EverythingMe/redash/blob/master/redash/query_runner/mongodb.py#L153

We should probably replace the `_fix_dates` method with usage of `object_hook` option of `json.loads`, as shown here:

![image](https://cloud.githubusercontent.com/assets/71468/10386214/d27e1204-6e5c-11e5-9aba-8829cccdefad.png)

(from: http://www.slideshare.net/nicolaiarocci/developing-restful-web-apis-with-python-flask-and-mongodb)

Just need to make sure that object_hook being invoked on inner dicts as well and not only top level.
